# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: GPG_GEN
env:
  GPG_KEY: ${{ secrets.MAVEN_SIGN_KEY }}
  GPG_KEY_ID: ${{ secrets.MAVEN_SIGN_KEY_ID }}
  GPG_PWD: ${{ secrets.MAVEN_SIGN_KEY_PWD }}
  PUB_USER: ${{ secrets.MAVEN_USER_NAME }}
  PUB_PWD: ${{ secrets.MAVEN_USER_PWD }}
on:
  workflow_dispatch:

jobs:
  pgp:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Publish
        run: |
          echo "Create .gpg key"
          echo "$MAVEN_SIGN_KEY" > ./release.asc
          gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc
          sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
          sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg,g" gradle.properties
          cat gradle.properties
