name: Sync Secrets to Another Repo

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository full name (owner/repo)'
        required: true

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secret: [MAVEN_SIGN_KEY, MAVEN_SIGN_KEY_ID, MAVEN_SIGN_KEY_PWD, MAVEN_USER_NAME, MAVEN_USER_PWD]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gh CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate gh CLI
        env:
          TARGET_REPO_PAT: ${{ secrets.SYNCSECRETSPAT }}
        run: |
          echo $TARGET_REPO_PAT | gh auth login --with-token

      - name: Sync Secret ${{ matrix.secret }}
        env:
          SECRET_VALUE: ${{ secrets[ matrix.secret ] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          echo "Syncing ${{ matrix.secret }} to $TARGET_REPO..."
          echo "$SECRET_VALUE" | gh secret set ${{ matrix.secret }} --repo $TARGET_REPO --body -
